download_directories:
  complete:
    movies: Z:\downloads\complete\movies
    tv_shows: Z:\downloads\complete\tv
  duplicate:
    movies: Z:\downloads\duplicate\movies
    tv_shows: Z:\downloads\duplicate\tv
  incomplete:
    movies: Z:\downloads\incomplete
    tv_shows: Z:\downloads\incomplete
media_libraries:
  movies: Z:\media\movies
  tv_shows:
    adult: Z:\media\tv_shows\adult
    kids: Z:\media\tv_shows\kids
logging:
  level: DEBUG
  file: logs/app.log
settings:
  movies:
    delete_failed: true
    delete_unpack: true
    days_to_keep_completed_downloads: 30
    days_to_keep_duplicate_downloads: 30
    days_to_keep_incomplete_downloads: 30
    move_to_duplicates: true
    move_to_library: true
  tv_shows:
    delete_failed: true
    delete_unpack: true
    days_to_keep_unpack: 2
    days_to_keep_completed_downloads: 30
    days_to_keep_duplicate_downloads: 30
    days_to_keep_incomplete_downloads: 30
    move_to_duplicates: true
    move_to_library: false
    season_folders: false

